-- ============================================================
-- Seed data for Business Template Library
-- ============================================================

-- 1. Template Categories
INSERT INTO template_categories (name, slug, icon, sort_order) VALUES
('Accounting', 'accounting', 'BookOpen', 1),
('Finance', 'finance', 'Landmark', 2),
('Sales', 'sales', 'Receipt', 3),
('Purchase', 'purchase', 'ShoppingBag', 4),
('Inventory', 'inventory', 'Package', 5),
('HR', 'hr', 'Users', 6),
('Operations', 'operations', 'Settings', 7),
('Project Management', 'project-management', 'CheckSquare', 8),
('Small Business', 'small-business', 'Briefcase', 9),
('Industry Specific', 'industry-specific', 'Layers', 10),
('Tax & Compliance', 'tax-compliance', 'ShieldCheck', 11),
('Personal/Professional Business', 'personal-business', 'UserCheck', 12)
ON CONFLICT (slug) DO NOTHING;

-- Helper function / INSERT for starter templates
INSERT INTO templates (name, slug, category_id, profession, description, file_type, version, source_type, license_note, fields_json, structure_json, preview_data_json, formula_notes, erp_data_source) VALUES

-- ------------------------------------------------------------
-- ACCOUNTING
-- ------------------------------------------------------------
(
  'Daily Cash Book',
  'daily-cash-book',
  (SELECT id FROM template_categories WHERE slug = 'accounting'),
  'Retail, Shops, Small Business, Cashier',
  'Track daily cash receipts, payments, and closing cash balance with automatic cumulative balance calculation.',
  'XLSX / CSV / PDF',
  '1.0.0',
  'Standard Business Format — Original',
  'Open Business Format — Free for commercial & operational use',
  '["Date", "Voucher No", "Description / Particulars", "Cash In (Receipt)", "Cash Out (Payment)", "Balance", "Remarks"]'::jsonb,
  '{"columns": [{"key": "date", "label": "Date", "type": "date"}, {"key": "voucher", "label": "Voucher No", "type": "text"}, {"key": "desc", "label": "Particulars", "type": "text"}, {"key": "in", "label": "Cash In (₹)", "type": "currency"}, {"key": "out", "label": "Cash Out (₹)", "type": "currency"}, {"key": "balance", "label": "Cash Balance (₹)", "type": "formula", "formula": "Opening + SUM(Cash In) - SUM(Cash Out)"}, {"key": "remarks", "label": "Remarks", "type": "text"}]}'::jsonb,
  '{"openingBalance": "50000.00", "rows": [{"date": "2026-09-01", "voucher": "CSH-001", "desc": "Opening Cash on Hand", "in": "0.00", "out": "0.00", "balance": "50000.00", "remarks": "Drawer start"}, {"date": "2026-09-01", "voucher": "REC-101", "desc": "Direct Customer Cash Sale - Coffee Table", "in": "12500.00", "out": "0.00", "balance": "62500.00", "remarks": "Walk-in client"}, {"date": "2026-09-01", "voucher": "PAY-042", "desc": "Local Workshop Hardware Supplies", "in": "0.00", "out": "2400.00", "balance": "60100.00", "remarks": "Drawer petty receipt"}, {"date": "2026-09-01", "voucher": "REC-102", "desc": "Sofa Upholstery Deposit", "in": "8000.00", "out": "0.00", "balance": "68100.00", "remarks": "Advance"}]}'::jsonb,
  'Closing Balance = Opening Balance + Total Cash In - Total Cash Out',
  NULL
),
(
  'Bank Book',
  'bank-book',
  (SELECT id FROM template_categories WHERE slug = 'accounting'),
  'Accountants, Business Owners, Finance Officers',
  'Record all bank deposits, cheque payments, NEFT/RTGS transfers, and bank charges against bank statement ledger.',
  'XLSX / CSV / PDF',
  '1.0.0',
  'Standard Business Format — Original',
  'Open Business Format — Free for commercial & operational use',
  '["Date", "Bank Reference / Cheque No", "Particulars", "Deposit / Debit (₹)", "Withdrawal / Credit (₹)", "Bank Balance (₹)", "Reconciliation Status"]'::jsonb,
  '{"columns": [{"key": "date", "label": "Date", "type": "date"}, {"key": "ref", "label": "Ref / Cheque #", "type": "text"}, {"key": "desc", "label": "Particulars", "type": "text"}, {"key": "deposit", "label": "Deposit (₹)", "type": "currency"}, {"key": "withdrawal", "label": "Withdrawal (₹)", "type": "currency"}, {"key": "balance", "label": "Bank Balance (₹)", "type": "formula"}, {"key": "status", "label": "Status", "type": "text"}]}'::jsonb,
  '{"openingBalance": "250000.00", "rows": [{"date": "2026-09-02", "ref": "NEFT-78192", "desc": "Customer Invoice Payment - Apex Interior", "deposit": "85000.00", "withdrawal": "0.00", "balance": "335000.00", "status": "Cleared"}, {"date": "2026-09-02", "ref": "CHQ-00451", "desc": "Timber Supplier Payment - Green Woods", "deposit": "0.00", "withdrawal": "64000.00", "balance": "271000.00", "status": "Cleared"}]}'::jsonb,
  'Closing Bank Balance = Opening Balance + Deposits - Withdrawals',
  NULL
),
(
  'Petty Cash Register',
  'petty-cash-register',
  (SELECT id FROM template_categories WHERE slug = 'accounting'),
  'Office Administrators, Front Desk, Supervisors',
  'Track small everyday company expenses using the imprest petty cash system with receipt vouchers.',
  'XLSX / CSV / PDF',
  '1.0.0',
  'Standard Business Format — Original',
  'Open Business Format — Free for commercial & operational use',
  '["Date", "Voucher #", "Expense Head", "Paid To", "Amount (₹)", "Remaining Imprest (₹)", "Approved By"]'::jsonb,
  '{"columns": [{"key": "date", "label": "Date", "type": "date"}, {"key": "voucher", "label": "Voucher #", "type": "text"}, {"key": "head", "label": "Expense Head", "type": "text"}, {"key": "paidTo", "label": "Paid To", "type": "text"}, {"key": "amount", "label": "Amount (₹)", "type": "currency"}, {"key": "balance", "label": "Remaining Imprest (₹)", "type": "formula"}, {"key": "approvedBy", "label": "Approved By", "type": "text"}]}'::jsonb,
  '{"openingBalance": "10000.00", "rows": [{"date": "2026-09-03", "voucher": "PC-01", "head": "Tea & Refreshments", "paidTo": "Chai Corner", "amount": "450.00", "balance": "9550.00", "approvedBy": "Manager"}, {"date": "2026-09-03", "voucher": "PC-02", "head": "Courier & Postage", "paidTo": "SpeedPost", "amount": "180.00", "balance": "9370.00", "approvedBy": "Admin"}]}'::jsonb,
  'Imprest Balance = Total Float - SUM(Expenses)',
  NULL
),
(
  'Expense Tracker',
  'expense-tracker',
  (SELECT id FROM template_categories WHERE slug = 'accounting'),
  'Freelancers, Small Businesses, Consultants',
  'Categorize operational and administrative expenses across heads with monthly subtotals and tax deduction tracking.',
  'XLSX / CSV / PDF',
  '1.0.0',
  'Standard Business Format — Original',
  'Open Business Format — Free for commercial & operational use',
  '["Date", "Category", "Vendor / Payee", "Payment Mode", "Taxable Amount (₹)", "GST / Tax (₹)", "Total Expense (₹)"]'::jsonb,
  '{"columns": [{"key": "date", "label": "Date", "type": "date"}, {"key": "category", "label": "Category", "type": "text"}, {"key": "payee", "label": "Payee", "type": "text"}, {"key": "mode", "label": "Mode", "type": "text"}, {"key": "taxable", "label": "Taxable Amount (₹)", "type": "currency"}, {"key": "tax", "label": "Tax (₹)", "type": "currency"}, {"key": "total", "label": "Total (₹)", "type": "formula", "formula": "Taxable + Tax"}]}'::jsonb,
  '{"rows": [{"date": "2026-09-01", "category": "Rent & Facility", "payee": "Showroom Landlord", "mode": "Bank Transfer", "taxable": "45000.00", "tax": "8100.00", "total": "53100.00"}, {"date": "2026-09-02", "category": "Utilities", "payee": "State Electricity Board", "mode": "Net Banking", "taxable": "6800.00", "tax": "0.00", "total": "6800.00"}]}'::jsonb,
  'Total Expense = Taxable Amount + GST / Tax',
  NULL
),
(
  'Income Tracker',
  'income-tracker',
  (SELECT id FROM template_categories WHERE slug = 'accounting'),
  'Sole Proprietors, Freelancers, Clinics, Contractors',
  'Monitor revenue streams, customer invoices, payment modes, and receivables status in one place.',
  'XLSX / CSV / PDF',
  '1.0.0',
  'Standard Business Format — Original',
  'Open Business Format — Free for commercial & operational use',
  '["Date", "Source / Stream", "Client Name", "Invoice #", "Gross Income (₹)", "Deductions / TDS (₹)", "Net Received (₹)"]'::jsonb,
  '{"columns": [{"key": "date", "label": "Date", "type": "date"}, {"key": "source", "label": "Revenue Stream", "type": "text"}, {"key": "client", "label": "Client Name", "type": "text"}, {"key": "invoice", "label": "Invoice #", "type": "text"}, {"key": "gross", "label": "Gross Income (₹)", "type": "currency"}, {"key": "tds", "label": "TDS / Ded (₹)", "type": "currency"}, {"key": "net", "label": "Net Received (₹)", "type": "formula", "formula": "Gross - TDS"}]}'::jsonb,
  '{"rows": [{"date": "2026-09-01", "source": "Custom Furniture Crafting", "client": "Heritage Living", "invoice": "INV/2026/001", "gross": "95000.00", "tds": "1900.00", "net": "93100.00"}]}'::jsonb,
  'Net Income = Gross Income - TDS / Deductions',
  NULL
),
(
  'Accounts Receivable Register',
  'accounts-receivable-register',
  (SELECT id FROM template_categories WHERE slug = 'accounting'),
  'Accountants, Credit Controllers, Sales Teams',
  'Complete register of all customer invoices, payment receipts, aging brackets, and pending credit balances.',
  'XLSX / CSV / PDF',
  '1.0.0',
  'Urban Furniture ERP — Original Template',
  'Open Business Format — Free for commercial & operational use',
  '["Invoice Date", "Invoice #", "Customer Name", "Invoice Amount (₹)", "Amount Received (₹)", "Balance Due (₹)", "Due Date", "Days Overdue"]'::jsonb,
  '{"columns": [{"key": "date", "label": "Invoice Date", "type": "date"}, {"key": "invoice", "label": "Invoice #", "type": "text"}, {"key": "customer", "label": "Customer", "type": "text"}, {"key": "amount", "label": "Invoice Amount (₹)", "type": "currency"}, {"key": "paid", "label": "Amount Received (₹)", "type": "currency"}, {"key": "due", "label": "Balance Due (₹)", "type": "formula", "formula": "Invoice Amount - Amount Received"}, {"key": "dueDate", "label": "Due Date", "type": "date"}, {"key": "overdueDays", "label": "Days Overdue", "type": "number"}]}'::jsonb,
  '{"rows": [{"date": "2026-08-15", "invoice": "INV/2026/002", "customer": "Decora Homes", "amount": "145000.00", "paid": "50000.00", "due": "95000.00", "dueDate": "2026-08-30", "overdueDays": 7}]}'::jsonb,
  'Balance Due = Total Invoice - Total Received. Days Overdue = MAX(0, Current Date - Due Date)',
  'customer_invoices'
),
(
  'Accounts Payable Register',
  'accounts-payable-register',
  (SELECT id FROM template_categories WHERE slug = 'accounting'),
  'Purchasing Agents, Finance Managers, Procurement',
  'Track vendor bills, credit terms, outgoing payments, and remaining liabilities to maintain good vendor relationships.',
  'XLSX / CSV / PDF',
  '1.0.0',
  'Urban Furniture ERP — Original Template',
  'Open Business Format — Free for commercial & operational use',
  '["Bill Date", "Bill #", "Vendor Name", "Bill Total (₹)", "Amount Paid (₹)", "Balance Payable (₹)", "Due Date", "Payment Status"]'::jsonb,
  '{"columns": [{"key": "date", "label": "Bill Date", "type": "date"}, {"key": "bill", "label": "Bill #", "type": "text"}, {"key": "vendor", "label": "Vendor", "type": "text"}, {"key": "amount", "label": "Bill Total (₹)", "type": "currency"}, {"key": "paid", "label": "Amount Paid (₹)", "type": "currency"}, {"key": "due", "label": "Balance Payable (₹)", "type": "formula", "formula": "Bill Total - Amount Paid"}, {"key": "dueDate", "label": "Due Date", "type": "date"}, {"key": "status", "label": "Status", "type": "text"}]}'::jsonb,
  '{"rows": [{"date": "2026-08-20", "bill": "BILL/2026/001", "vendor": "Timber Craft Sawmills", "amount": "82000.00", "paid": "40000.00", "due": "42000.00", "dueDate": "2026-09-10", "status": "Partially Paid"}]}'::jsonb,
  'Balance Payable = Bill Total - Amount Paid',
  'vendor_bills'
),
(
  'Customer Outstanding Statement',
  'customer-outstanding-statement',
  (SELECT id FROM template_categories WHERE slug = 'accounting'),
  'Sales Representatives, Credit Managers',
  'Client-facing account statement showing all billed invoices, payments received, credit notes, and net balance due.',
  'XLSX / CSV / PDF',
  '1.0.0',
  'Urban Furniture ERP — Original Template',
  'Open Business Format — Free for commercial & operational use',
  '["Date", "Doc Ref", "Transaction Type", "Debit / Invoiced (₹)", "Credit / Received (₹)", "Running Balance (₹)"]'::jsonb,
  '{"columns": [{"key": "date", "label": "Date", "type": "date"}, {"key": "doc", "label": "Doc Ref #", "type": "text"}, {"key": "type", "label": "Type", "type": "text"}, {"key": "debit", "label": "Billed (₹)", "type": "currency"}, {"key": "credit", "label": "Paid (₹)", "type": "currency"}, {"key": "balance", "label": "Running Due (₹)", "type": "formula"}]}'::jsonb,
  '{"openingBalance": "0.00", "rows": [{"date": "2026-08-01", "doc": "INV/2026/004", "type": "Customer Invoice", "debit": "120000.00", "credit": "0.00", "balance": "120000.00"}, {"date": "2026-08-10", "doc": "PAY/2026/003", "type": "Bank Receipt", "debit": "0.00", "credit": "70000.00", "balance": "50000.00"}]}'::jsonb,
  'Running Due = Prior Balance + Billed Amount - Paid Amount',
  'customer_outstanding'
),
(
  'Vendor Outstanding Statement',
  'vendor-outstanding-statement',
  (SELECT id FROM template_categories WHERE slug = 'accounting'),
  'Accountants, Accounts Payable, Procurement',
  'Statement of account for suppliers detailing received bills, payments disbursed, and net pending liability.',
  'XLSX / CSV / PDF',
  '1.0.0',
  'Urban Furniture ERP — Original Template',
  'Open Business Format — Free for commercial & operational use',
  '["Date", "Bill / Voucher Ref", "Transaction", "Purchases / Credit (₹)", "Payments / Debit (₹)", "Outstanding Balance (₹)"]'::jsonb,
  '{"columns": [{"key": "date", "label": "Date", "type": "date"}, {"key": "ref", "label": "Ref #", "type": "text"}, {"key": "desc", "label": "Transaction", "type": "text"}, {"key": "credit", "label": "Purchases (₹)", "type": "currency"}, {"key": "debit", "label": "Payments (₹)", "type": "currency"}, {"key": "balance", "label": "Net Payable (₹)", "type": "formula"}]}'::jsonb,
  '{"openingBalance": "0.00", "rows": [{"date": "2026-08-05", "ref": "BILL/2026/008", "desc": "Hardware & Fittings Supply", "credit": "45000.00", "debit": "0.00", "balance": "45000.00"}, {"date": "2026-08-25", "ref": "PAY/2026/005", "desc": "NEFT Outbound Settlement", "credit": "0.00", "debit": "45000.00", "balance": "0.00"}]}'::jsonb,
  'Net Payable = Prior Balance + Purchases - Payments',
  'vendor_outstanding'
),
(
  'General Ledger',
  'general-ledger',
  (SELECT id FROM template_categories WHERE slug = 'accounting'),
  'Chartered Accountants, Financial Controllers',
  'Master general ledger schedule showing chronological debits and credits posted to accounts with running balance.',
  'XLSX / CSV / PDF',
  '1.0.0',
  'Standard Business Format — Original',
  'Open Business Format — Free for commercial & operational use',
  '["Posting Date", "Entry #", "Account Code", "Account Name", "Debit (₹)", "Credit (₹)", "Running Balance (₹)"]'::jsonb,
  '{"columns": [{"key": "date", "label": "Posting Date", "type": "date"}, {"key": "entry", "label": "Entry #", "type": "text"}, {"key": "code", "label": "Account Code", "type": "text"}, {"key": "name", "label": "Account Name", "type": "text"}, {"key": "debit", "label": "Debit (₹)", "type": "currency"}, {"key": "credit", "label": "Credit (₹)", "type": "currency"}, {"key": "balance", "label": "Balance (₹)", "type": "formula"}]}'::jsonb,
  '{"rows": [{"date": "2026-09-01", "entry": "JE/2026/001", "code": "1200", "name": "Sundry Debtors", "debit": "59000.00", "credit": "0.00", "balance": "59000.00"}, {"date": "2026-09-01", "entry": "JE/2026/001", "code": "4000", "name": "Sales Revenue", "debit": "0.00", "credit": "50000.00", "balance": "50000.00"}]}'::jsonb,
  'Debit = Credit invariant enforced across every posted entry.',
  'general_ledger'
),
(
  'Trial Balance',
  'trial-balance',
  (SELECT id FROM template_categories WHERE slug = 'accounting'),
  'Auditors, Accountants, Tax Professionals',
  'Summary trial balance listing all accounts with respective debit and credit balances proving double-entry equilibrium.',
  'XLSX / CSV / PDF',
  '1.0.0',
  'Standard Business Format — Original',
  'Open Business Format — Free for commercial & operational use',
  '["Account Code", "Account Title", "Account Type", "Debit Total (₹)", "Credit Total (₹)", "Net Balance (₹)"]'::jsonb,
  '{"columns": [{"key": "code", "label": "Code", "type": "text"}, {"key": "title", "label": "Account Title", "type": "text"}, {"key": "type", "label": "Type", "type": "text"}, {"key": "debit", "label": "Debit Total (₹)", "type": "currency"}, {"key": "credit", "label": "Credit Total (₹)", "type": "currency"}, {"key": "net", "label": "Net Balance (₹)", "type": "formula"}]}'::jsonb,
  '{"rows": [{"code": "1010", "title": "Cash Drawer", "type": "Asset", "debit": "75000.00", "credit": "25000.00", "net": "50000.00 Dr"}, {"code": "1020", "title": "Bank Account", "type": "Asset", "debit": "420000.00", "credit": "110000.00", "net": "310000.00 Dr"}, {"code": "2010", "title": "Sundry Creditors", "type": "Liability", "debit": "60000.00", "credit": "150000.00", "net": "90000.00 Cr"}]}'::jsonb,
  'Total Debits must equal Total Credits: SUM(Debits) == SUM(Credits)',
  NULL
),
(
  'Profit & Loss Format',
  'profit-and-loss-format',
  (SELECT id FROM template_categories WHERE slug = 'accounting'),
  'Business Owners, Executives, Analysts',
  'Standard P&L Income Statement separating Revenue, Cost of Goods Sold, Gross Profit, Operating Expenses, and Net Profit.',
  'XLSX / CSV / PDF',
  '1.0.0',
  'Standard Business Format — Original',
  'Open Business Format — Free for commercial & operational use',
  '["Particulars", "Schedule / Note", "Current Month (₹)", "YTD (₹)", "% of Revenue"]'::jsonb,
  '{"columns": [{"key": "particulars", "label": "Particulars", "type": "text"}, {"key": "note", "label": "Schedule", "type": "text"}, {"key": "month", "label": "Current Period (₹)", "type": "currency"}, {"key": "ytd", "label": "YTD (₹)", "type": "currency"}, {"key": "pct", "label": "% Revenue", "type": "text"}]}'::jsonb,
  '{"rows": [{"particulars": "Gross Operating Revenue", "note": "Sch-1", "month": "850000.00", "ytd": "3400000.00", "pct": "100.0%"}, {"particulars": "Cost of Goods Sold (Materials + Direct Labour)", "note": "Sch-2", "month": "420000.00", "ytd": "1680000.00", "pct": "49.4%"}, {"particulars": "GROSS PROFIT", "note": "Total", "month": "430000.00", "ytd": "1720000.00", "pct": "50.6%"}, {"particulars": "Administrative & Selling Expenses", "note": "Sch-3", "month": "145000.00", "ytd": "580000.00", "pct": "17.1%"}, {"particulars": "NET PROFIT BEFORE TAX", "note": "Operating", "month": "285000.00", "ytd": "1140000.00", "pct": "33.5%"}]}'::jsonb,
  'Gross Profit = Revenue - COGS; Net Profit = Gross Profit - Operating Expenses',
  'pnl'
),
(
  'Classified Balance Sheet Format',
  'balance-sheet-format',
  (SELECT id FROM template_categories WHERE slug = 'accounting'),
  'CFOs, Accountants, Financial Analysts, Directors',
  'Standard classified balance sheet dividing Assets into Current and Non-Current, Liabilities into Current and Long-Term, and Equity with live ERP ledger binding.',
  'XLSX / CSV / PDF',
  '1.0.0',
  'Standard Business Format — Original',
  'Open Business Format — Free for commercial & operational use',
  '["Balance Sheet Item", "Classification", "Current Period (₹)", "Prior Period (₹)"]'::jsonb,
  '{"columns": [{"key": "item", "label": "Balance Sheet Item", "type": "text"}, {"key": "classification", "label": "Classification", "type": "text"}, {"key": "amount", "label": "Current Period (₹)", "type": "currency"}, {"key": "prior", "label": "Prior Period (₹)", "type": "currency"}]}'::jsonb,
  '{"rows": [{"item": "CURRENT ASSETS", "classification": "Header", "amount": "", "prior": ""}, {"item": "  Cash & Cash Equivalents", "classification": "Current Asset", "amount": "167971.00", "prior": "181210.00"}, {"item": "  Accounts Receivable", "classification": "Current Asset", "amount": "51000.00", "prior": "59040.00"}, {"item": "  Prepaid Expenses", "classification": "Current Asset", "amount": "48060.00", "prior": "55130.00"}, {"item": "  Inventories", "classification": "Current Asset", "amount": "78050.00", "prior": "96010.00"}, {"item": "TOTAL CURRENT ASSETS", "classification": "Subtotal", "amount": "345081.00", "prior": "391390.00"}, {"item": "NON-CURRENT ASSETS", "classification": "Header", "amount": "", "prior": ""}, {"item": "  Property, Plant & Equipment (PP&E)", "classification": "Fixed Asset", "amount": "455000.00", "prior": "423500.00"}, {"item": "  Goodwill & Intangible Assets", "classification": "Intangible Asset", "amount": "35800.00", "prior": "34600.00"}, {"item": "TOTAL ASSETS", "classification": "Total", "amount": "835881.00", "prior": "849490.00"}, {"item": "CURRENT LIABILITIES", "classification": "Header", "amount": "", "prior": ""}, {"item": "  Accounts Payable", "classification": "Current Liability", "amount": "39020.00", "prior": "48000.00"}, {"item": "  Accrued Expenses & Taxes", "classification": "Current Liability", "amount": "13200.00", "prior": "15410.00"}, {"item": "  Unearned Revenue", "classification": "Current Liability", "amount": "15400.00", "prior": "15600.00"}, {"item": "TOTAL CURRENT LIABILITIES", "classification": "Subtotal", "amount": "67620.00", "prior": "79010.00"}, {"item": "NON-CURRENT LIABILITIES", "classification": "Header", "amount": "", "prior": ""}, {"item": "  Long-Term Debt", "classification": "Long-Term Liability", "amount": "500000.00", "prior": "500000.00"}, {"item": "  Other Long-Term Liabilities", "classification": "Long-Term Liability", "amount": "55260.00", "prior": "58720.00"}, {"item": "TOTAL LIABILITIES", "classification": "Subtotal", "amount": "622880.00", "prior": "637730.00"}, {"item": "SHAREHOLDERS’ EQUITY", "classification": "Header", "amount": "", "prior": ""}, {"item": "  Share Capital / Owner Investment", "classification": "Equity", "amount": "170000.00", "prior": "170000.00"}, {"item": "  Retained Earnings", "classification": "Equity", "amount": "43001.00", "prior": "41760.00"}, {"item": "TOTAL SHAREHOLDERS’ EQUITY", "classification": "Subtotal", "amount": "213001.00", "prior": "211760.00"}, {"item": "TOTAL LIABILITIES & EQUITY", "classification": "Total", "amount": "835881.00", "prior": "849490.00"}, {"item": "Check (Assets - Liabilities & Equity)", "classification": "Check", "amount": "0.00", "prior": "0.00"}]}'::jsonb,
  'Accounting Equation: Assets = Liabilities + Equity | Total Current Assets = Sum(Current Assets) | Total Assets = Current Assets + Non-Current Assets | Total Liabilities & Equity = Total Liabilities + Shareholders Equity | Check = Total Assets - Total Liabilities & Equity = 0.00',
  'balance_sheet'
),
(
  'Corporate Consolidated Balance Sheet (Form 10-K)',
  'corporate-consolidated-balance-sheet',
  (SELECT id FROM template_categories WHERE slug = 'accounting'),
  'Corporate Controllers, SEC Filers, External Auditors, CFOs',
  'Consolidated corporate balance sheet formatted per SEC Form 10-K standards with marketable securities, leases, equity breakdown, and balance check.',
  'XLSX / CSV / PDF',
  '1.0.0',
  'US GAAP / SEC Form 10-K Standard Format',
  'Open Business Format — Free for commercial & operational use',
  '["Balance Sheet Item", "December 31, 2024 ($/₹ M)", "December 31, 2023 ($/₹ M)"]'::jsonb,
  '{"columns": [{"key": "item", "label": "Balance Sheet Item", "type": "text"}, {"key": "current_yr", "label": "Current Period ($/₹ M)", "type": "currency"}, {"key": "prior_yr", "label": "Prior Period ($/₹ M)", "type": "currency"}]}'::jsonb,
  '{"rows": [{"item": "CURRENT ASSETS", "current_yr": "", "prior_yr": ""}, {"item": "  Cash and cash equivalents", "current_yr": "78779.00", "prior_yr": "73387.00"}, {"item": "  Marketable securities", "current_yr": "22423.00", "prior_yr": "13393.00"}, {"item": "  Inventories", "current_yr": "34214.00", "prior_yr": "33318.00"}, {"item": "  Accounts receivable, net and other", "current_yr": "55451.00", "prior_yr": "52253.00"}, {"item": "TOTAL CURRENT ASSETS", "current_yr": "190867.00", "prior_yr": "172351.00"}, {"item": "NON-CURRENT ASSETS", "current_yr": "", "prior_yr": ""}, {"item": "  Property and equipment, net", "current_yr": "252665.00", "prior_yr": "204177.00"}, {"item": "  Operating leases", "current_yr": "76141.00", "prior_yr": "72513.00"}, {"item": "  Goodwill", "current_yr": "23074.00", "prior_yr": "22789.00"}, {"item": "  Other assets", "current_yr": "82147.00", "prior_yr": "56024.00"}, {"item": "TOTAL ASSETS", "current_yr": "624894.00", "prior_yr": "527854.00"}, {"item": "CURRENT LIABILITIES", "current_yr": "", "prior_yr": ""}, {"item": "  Accounts payable", "current_yr": "94363.00", "prior_yr": "84981.00"}, {"item": "  Accrued expenses and other", "current_yr": "66965.00", "prior_yr": "64709.00"}, {"item": "  Unearned revenue", "current_yr": "18103.00", "prior_yr": "15227.00"}, {"item": "TOTAL CURRENT LIABILITIES", "current_yr": "179431.00", "prior_yr": "164917.00"}, {"item": "NON-CURRENT LIABILITIES", "current_yr": "", "prior_yr": ""}, {"item": "  Long-term lease liabilities", "current_yr": "78277.00", "prior_yr": "77297.00"}, {"item": "  Long-term debt", "current_yr": "52623.00", "prior_yr": "58314.00"}, {"item": "  Other long-term liabilities", "current_yr": "28593.00", "prior_yr": "25451.00"}, {"item": "TOTAL LIABILITIES", "current_yr": "338924.00", "prior_yr": "325979.00"}, {"item": "STOCKHOLDERS’ EQUITY", "current_yr": "", "prior_yr": ""}, {"item": "  Common stock", "current_yr": "111.00", "prior_yr": "109.00"}, {"item": "  Treasury stock", "current_yr": "-7837.00", "prior_yr": "-7837.00"}, {"item": "  Additional paid-in capital", "current_yr": "120864.00", "prior_yr": "99025.00"}, {"item": "  Accumulated other comprehensive loss", "current_yr": "-34.00", "prior_yr": "-3040.00"}, {"item": "  Retained earnings", "current_yr": "172866.00", "prior_yr": "113618.00"}, {"item": "TOTAL STOCKHOLDERS’ EQUITY", "current_yr": "285970.00", "prior_yr": "201875.00"}, {"item": "TOTAL LIABILITIES AND STOCKHOLDERS’ EQUITY", "current_yr": "624894.00", "prior_yr": "527854.00"}, {"item": "Check (Total Assets - Total Liab & Equity)", "current_yr": "0.00", "prior_yr": "0.00"}]}'::jsonb,
  'Accounting Balance: Assets = Liabilities + Equity | Total Current Assets = Cash + Securities + Inventories + Receivables | Total Assets = Current Assets + PP&E + Leases + Goodwill + Other | Total Liabilities & Stockholders Equity = Total Liabilities + Total Stockholders Equity | Check = Total Assets - Total Liab & Equity = 0.00',
  NULL
),
(
  'Multi-Year Financial Model Balance Sheet',
  'multi-year-balance-sheet-model',
  (SELECT id FROM template_categories WHERE slug = 'finance'),
  'Financial Modelers, Investment Bankers, Analysts, Controllers',
  'CFI-style 5-year financial analysis balance sheet tracking Current Assets, PP&E, Debt, Equity, and Retained Earnings with accounting balance check across 5 periods.',
  'XLSX / CSV / PDF',
  '1.0.0',
  'Corporate Finance Institute (CFI) Standard Model',
  'Open Business Format — Free for commercial & operational use',
  '["Balance Sheet Item", "Year 1 (₹)", "Year 2 (₹)", "Year 3 (₹)", "Year 4 (₹)", "Year 5 (₹)"]'::jsonb,
  '{"columns": [{"key": "item", "label": "Balance Sheet Item", "type": "text"}, {"key": "y1", "label": "Year 1 (₹)", "type": "currency"}, {"key": "y2", "label": "Year 2 (₹)", "type": "currency"}, {"key": "y3", "label": "Year 3 (₹)", "type": "currency"}, {"key": "y4", "label": "Year 4 (₹)", "type": "currency"}, {"key": "y5", "label": "Year 5 (₹)", "type": "currency"}]}'::jsonb,
  '{"rows": [{"item": "CURRENT ASSETS", "y1": "", "y2": "", "y3": "", "y4": "", "y5": ""}, {"item": "  Cash & Cash Equivalents", "y1": "91350.00", "y2": "87050.00", "y3": "68670.00", "y4": "67560.00", "y5": "77220.00"}, {"item": "  Accounts Receivable", "y1": "67780.00", "y2": "56240.00", "y3": "58350.00", "y4": "56140.00", "y5": "62830.00"}, {"item": "  Prepaid Expenses", "y1": "48060.00", "y2": "55130.00", "y3": "51700.00", "y4": "59980.00", "y5": "56820.00"}, {"item": "  Inventories", "y1": "473650.00", "y2": "459100.00", "y3": "449870.00", "y4": "472940.00", "y5": "478920.00"}, {"item": "TOTAL CURRENT ASSETS", "y1": "680840.00", "y2": "657520.00", "y3": "628590.00", "y4": "656620.00", "y5": "675790.00"}, {"item": "NON-CURRENT ASSETS", "y1": "", "y2": "", "y3": "", "y4": "", "y5": ""}, {"item": "  Property, Plant & Equipment (PP&E)", "y1": "1404280.00", "y2": "1393420.00", "y3": "1411360.00", "y4": "1448580.00", "y5": "1573980.00"}, {"item": "  Goodwill & Intangible Assets", "y1": "35800.00", "y2": "34600.00", "y3": "39100.00", "y4": "38700.00", "y5": "38500.00"}, {"item": "TOTAL ASSETS", "y1": "2120920.00", "y2": "2085540.00", "y3": "2079050.00", "y4": "2143900.00", "y5": "2288270.00"}, {"item": "CURRENT LIABILITIES", "y1": "", "y2": "", "y3": "", "y4": "", "y5": ""}, {"item": "  Accounts Payable", "y1": "585830.00", "y2": "586150.00", "y3": "630080.00", "y4": "688590.00", "y5": "696470.00"}, {"item": "  Accrued Expenses & Taxes", "y1": "66890.00", "y2": "60040.00", "y3": "39200.00", "y4": "96620.00", "y5": "78300.00"}, {"item": "TOTAL CURRENT LIABILITIES", "y1": "652720.00", "y2": "646190.00", "y3": "669280.00", "y4": "785210.00", "y5": "774770.00"}, {"item": "NON-CURRENT LIABILITIES", "y1": "", "y2": "", "y3": "", "y4": "", "y5": ""}, {"item": "  Long-Term Debt", "y1": "570400.00", "y2": "544160.00", "y3": "540990.00", "y4": "481320.00", "y5": "693220.00"}, {"item": "  Other Long-Term Liabilities", "y1": "55260.00", "y2": "58720.00", "y3": "55650.00", "y4": "60510.00", "y5": "59090.00"}, {"item": "TOTAL LIABILITIES", "y1": "1278380.00", "y2": "1249070.00", "y3": "1265920.00", "y4": "1327040.00", "y5": "1527080.00"}, {"item": "SHAREHOLDERS’ EQUITY", "y1": "", "y2": "", "y3": "", "y4": "", "y5": ""}, {"item": "  Common Equity / Share Capital", "y1": "278500.00", "y2": "212200.00", "y3": "267600.00", "y4": "294300.00", "y5": "325300.00"}, {"item": "  Retained Earnings", "y1": "564040.00", "y2": "624270.00", "y3": "545530.00", "y4": "522560.00", "y5": "435890.00"}, {"item": "TOTAL SHAREHOLDERS’ EQUITY", "y1": "842540.00", "y2": "836470.00", "y3": "813130.00", "y4": "816860.00", "y5": "761190.00"}, {"item": "TOTAL LIABILITIES & EQUITY", "y1": "2120920.00", "y2": "2085540.00", "y3": "2079050.00", "y4": "2143900.00", "y5": "2288270.00"}, {"item": "Check (Assets - Liabilities & Equity)", "y1": "0.00", "y2": "0.00", "y3": "0.00", "y4": "0.00", "y5": "0.00"}]}'::jsonb,
  'Total Assets = Total Current Assets + PP&E + Goodwill | Total Liabilities = Total Current Liabilities + Long-Term Debt + Other Liabilities | Total Shareholders Equity = Common Equity + Retained Earnings | Check = Total Assets - Total Liabilities & Equity = 0.000',
  NULL
),

-- ------------------------------------------------------------
-- SALES
-- ------------------------------------------------------------
(
  'Sales Register',
  'sales-register',
  (SELECT id FROM template_categories WHERE slug = 'sales'),
  'Sales Managers, Retailers, Wholesalers',
  'Comprehensive log of all outgoing sales with invoice numbers, customer names, taxable amounts, and tax collected.',
  'XLSX / CSV / PDF',
  '1.0.0',
  'Urban Furniture ERP — Original Template',
  'Open Business Format — Free for commercial & operational use',
  '["Date", "Invoice #", "Customer", "GSTIN", "Taxable Value (₹)", "CGST (₹)", "SGST (₹)", "IGST (₹)", "Total Invoice (₹)"]'::jsonb,
  '{"columns": [{"key": "date", "label": "Date", "type": "date"}, {"key": "invoice", "label": "Invoice #", "type": "text"}, {"key": "customer", "label": "Customer", "type": "text"}, {"key": "gstin", "label": "GSTIN", "type": "text"}, {"key": "taxable", "label": "Taxable Value (₹)", "type": "currency"}, {"key": "cgst", "label": "CGST (₹)", "type": "currency"}, {"key": "sgst", "label": "SGST (₹)", "type": "currency"}, {"key": "igst", "label": "IGST (₹)", "type": "currency"}, {"key": "total", "label": "Total Invoice (₹)", "type": "formula", "formula": "Taxable + CGST + SGST + IGST"}]}'::jsonb,
  '{"rows": [{"date": "2026-09-01", "invoice": "INV/2026/001", "customer": "Royal Comforts", "gstin": "27AABCR1234F1Z1", "taxable": "50000.00", "cgst": "4500.00", "sgst": "4500.00", "igst": "0.00", "total": "59000.00"}]}'::jsonb,
  'Total Invoice = Taxable Value + CGST + SGST + IGST',
  'customer_invoices'
),
(
  'Sales Invoice',
  'sales-invoice',
  (SELECT id FROM template_categories WHERE slug = 'sales'),
  'All Businesses, Service Providers, Shops',
  'Professional standard business tax invoice with line item quantities, rates, discounts, GST calculation, and terms.',
  'XLSX / CSV / PDF',
  '1.0.0',
  'Standard Business Format — Original',
  'Open Business Format — Free for commercial & operational use',
  '["Item Description", "HSN/SAC", "Quantity", "Unit Rate (₹)", "Discount (%)", "Taxable (₹)", "Tax Rate (%)", "Total (₹)"]'::jsonb,
  '{"columns": [{"key": "desc", "label": "Item Description", "type": "text"}, {"key": "hsn", "label": "HSN Code", "type": "text"}, {"key": "qty", "label": "Qty", "type": "number"}, {"key": "rate", "label": "Unit Rate (₹)", "type": "currency"}, {"key": "disc", "label": "Disc %", "type": "number"}, {"key": "taxable", "label": "Taxable (₹)", "type": "formula", "formula": "Qty * Rate * (1 - Disc/100)"}, {"key": "taxRate", "label": "Tax %", "type": "number"}, {"key": "total", "label": "Total (₹)", "type": "formula", "formula": "Taxable * (1 + TaxRate/100)"}]}'::jsonb,
  '{"rows": [{"desc": "Teak Wood Executive Desk", "hsn": "9403", "qty": 2, "rate": "35000.00", "disc": 5, "taxable": "66500.00", "taxRate": 18, "total": "78470.00"}]}'::jsonb,
  'Subtotal = Qty * Rate * (1 - Disc%); Grand Total = Subtotal + (Subtotal * Tax%)',
  NULL
),
(
  'Quotation',
  'quotation',
  (SELECT id FROM template_categories WHERE slug = 'sales'),
  'Sales Representatives, Contractors, Custom Designers',
  'Formal price quotation template with validity terms, milestone payment schedules, and scope description.',
  'XLSX / CSV / PDF',
  '1.0.0',
  'Standard Business Format — Original',
  'Open Business Format — Free for commercial & operational use',
  '["Item / Service", "Specification", "Estimated Qty", "Quoted Rate (₹)", "Subtotal (₹)", "Remarks"]'::jsonb,
  '{"columns": [{"key": "item", "label": "Item", "type": "text"}, {"key": "spec", "label": "Specifications", "type": "text"}, {"key": "qty", "label": "Qty", "type": "number"}, {"key": "rate", "label": "Rate (₹)", "type": "currency"}, {"key": "subtotal", "label": "Subtotal (₹)", "type": "formula", "formula": "Qty * Rate"}, {"key": "remarks", "label": "Remarks", "type": "text"}]}'::jsonb,
  '{"rows": [{"item": "Conference Table (12-Seater)", "spec": "Walnut veneer, wire manager grommets", "qty": 1, "rate": "95000.00", "subtotal": "95000.00", "remarks": "Delivery within 14 days"}]}'::jsonb,
  'Subtotal = Qty * Quoted Rate; Total = SUM(Subtotals) + Applicable Tax',
  NULL
),
(
  'Sales Order',
  'sales-order',
  (SELECT id FROM template_categories WHERE slug = 'sales'),
  'Showrooms, Manufacturers, Distributors',
  'Confirmed customer sales order recording delivery dates, production milestones, advances, and shipping addresses.',
  'XLSX / CSV / PDF',
  '1.0.0',
  'Standard Business Format — Original',
  'Open Business Format — Free for commercial & operational use',
  '["Order Date", "SO #", "Client Name", "Total Value (₹)", "Advance Paid (₹)", "Balance on Delivery (₹)", "Dispatch Status"]'::jsonb,
  '{"columns": [{"key": "date", "label": "Order Date", "type": "date"}, {"key": "so", "label": "SO #", "type": "text"}, {"key": "client", "label": "Client", "type": "text"}, {"key": "value", "label": "Total Value (₹)", "type": "currency"}, {"key": "advance", "label": "Advance (₹)", "type": "currency"}, {"key": "balance", "label": "Balance (₹)", "type": "formula", "formula": "Total Value - Advance"}, {"key": "status", "label": "Status", "type": "text"}]}'::jsonb,
  '{"rows": [{"date": "2026-09-02", "so": "SO/2026/004", "client": "Skyline Builders", "value": "180000.00", "advance": "90000.00", "balance": "90000.00", "status": "In Production"}]}'::jsonb,
  'Balance on Delivery = Total Order Value - Advance Paid',
  NULL
),
(
  'Customer Payment Tracker',
  'customer-payment-tracker',
  (SELECT id FROM template_categories WHERE slug = 'sales'),
  'Collection Teams, Cashiers, Accountants',
  'Track collection receipts by customer, payment mode (Cheque, UPI, Wire), transaction references, and clearance.',
  'XLSX / CSV / PDF',
  '1.0.0',
  'Standard Business Format — Original',
  'Open Business Format — Free for commercial & operational use',
  '["Payment Date", "Receipt #", "Customer", "Invoice Settled", "Payment Mode", "Ref / UTR #", "Amount Received (₹)"]'::jsonb,
  '{"columns": [{"key": "date", "label": "Date", "type": "date"}, {"key": "receipt", "label": "Receipt #", "type": "text"}, {"key": "customer", "label": "Customer", "type": "text"}, {"key": "inv", "label": "Invoice Ref", "type": "text"}, {"key": "mode", "label": "Mode", "type": "text"}, {"key": "ref", "label": "UTR / Cheque #", "type": "text"}, {"key": "amount", "label": "Amount (₹)", "type": "currency"}]}'::jsonb,
  '{"rows": [{"date": "2026-09-03", "receipt": "RCP-012", "customer": "Decora Homes", "inv": "INV/2026/002", "mode": "NEFT", "ref": "HDFC0019284", "amount": "50000.00"}]}'::jsonb,
  'Total Collections = SUM(Amount Received)',
  NULL
),
(
  'Customer Follow-up Sheet',
  'customer-follow-up-sheet',
  (SELECT id FROM template_categories WHERE slug = 'sales'),
  'CRM Executives, Account Managers, Telecallers',
  'Record customer inquiries, quotation revisions, scheduled call-backs, and deal conversion probabilities.',
  'XLSX / CSV / PDF',
  '1.0.0',
  'Standard Business Format — Original',
  'Open Business Format — Free for commercial & operational use',
  '["Follow-up Date", "Client Name", "Contact Person", "Phone", "Quote Ref", "Discussion Summary", "Next Action Date", "Probability (%)"]'::jsonb,
  '{"columns": [{"key": "date", "label": "Date", "type": "date"}, {"key": "client", "label": "Client", "type": "text"}, {"key": "contact", "label": "Contact Person", "type": "text"}, {"key": "phone", "label": "Phone", "type": "text"}, {"key": "quote", "label": "Quote #", "type": "text"}, {"key": "notes", "label": "Notes", "type": "text"}, {"key": "nextDate", "label": "Next Action", "type": "date"}, {"key": "prob", "label": "Deal %", "type": "number"}]}'::jsonb,
  '{"rows": [{"date": "2026-09-04", "client": "Zenith Architects", "contact": "Rajesh Sharma", "phone": "+91 98201 22334", "quote": "QT-089", "notes": "Requested 5% discount on bulk wardrobe package", "nextDate": "2026-09-07", "prob": 80}]}'::jsonb,
  'Pipeline Value = Quoted Value * (Probability / 100)',
  NULL
),

-- ------------------------------------------------------------
-- PURCHASE
-- ------------------------------------------------------------
(
  'Purchase Register',
  'purchase-register',
  (SELECT id FROM template_categories WHERE slug = 'purchase'),
  'Procurement, Inventory Controllers, Accountants',
  'Detailed record of all vendor purchase bills, input GST credits (CGST/SGST/IGST), and total inventory acquisitions.',
  'XLSX / CSV / PDF',
  '1.0.0',
  'Urban Furniture ERP — Original Template',
  'Open Business Format — Free for commercial & operational use',
  '["Bill Date", "Bill #", "Supplier / Vendor", "GSTIN", "Taxable Amount (₹)", "Input Tax Credit (₹)", "Total Bill (₹)"]'::jsonb,
  '{"columns": [{"key": "date", "label": "Date", "type": "date"}, {"key": "bill", "label": "Bill #", "type": "text"}, {"key": "vendor", "label": "Vendor", "type": "text"}, {"key": "gstin", "label": "GSTIN", "type": "text"}, {"key": "taxable", "label": "Taxable (₹)", "type": "currency"}, {"key": "itc", "label": "Input Tax (₹)", "type": "currency"}, {"key": "total", "label": "Total Bill (₹)", "type": "formula", "formula": "Taxable + ITC"}]}'::jsonb,
  '{"rows": [{"date": "2026-08-28", "bill": "BILL/2026/014", "vendor": "Century Plyboards", "gstin": "27AAACC4455G1Z9", "taxable": "110000.00", "itc": "19800.00", "total": "129800.00"}]}'::jsonb,
  'Total Bill = Taxable Amount + Input Tax Credit (CGST + SGST)',
  'vendor_bills'
),
(
  'Purchase Order',
  'purchase-order',
  (SELECT id FROM template_categories WHERE slug = 'purchase'),
  'Purchasing Officers, Project Managers',
  'Official commercial purchase order issued to vendors detailing items, required specifications, delivery terms, and agreed rates.',
  'XLSX / CSV / PDF',
  '1.0.0',
  'Standard Business Format — Original',
  'Open Business Format — Free for commercial & operational use',
  '["Item Description", "Specification / Grade", "Quantity", "Unit Rate (₹)", "Subtotal (₹)", "Expected Delivery Date"]'::jsonb,
  '{"columns": [{"key": "item", "label": "Item", "type": "text"}, {"key": "spec", "label": "Specification", "type": "text"}, {"key": "qty", "label": "Qty", "type": "number"}, {"key": "rate", "label": "Rate (₹)", "type": "currency"}, {"key": "subtotal", "label": "Subtotal (₹)", "type": "formula", "formula": "Qty * Rate"}, {"key": "deliveryDate", "label": "Delivery Date", "type": "date"}]}'::jsonb,
  '{"rows": [{"item": "Commercial Plywood (19mm)", "spec": "IS:303 BWR Grade 8x4 ft", "qty": 40, "rate": "2200.00", "subtotal": "88000.00", "deliveryDate": "2026-09-08"}]}'::jsonb,
  'Subtotal = Quantity * Unit Rate; Total PO = SUM(Subtotals) + Applicable Taxes',
  NULL
),
(
  'Vendor Bill Register',
  'vendor-bill-register',
  (SELECT id FROM template_categories WHERE slug = 'purchase'),
  'Finance, Store Managers',
  'Register of incoming vendor bills matching POs, delivery challans, goods received notes (GRN), and payment statuses.',
  'XLSX / CSV / PDF',
  '1.0.0',
  'Standard Business Format — Original',
  'Open Business Format — Free for commercial & operational use',
  '["Date", "Bill Ref", "PO Ref", "Vendor", "Amount (₹)", "Due Date", "Approval Status"]'::jsonb,
  '{"columns": [{"key": "date", "label": "Date", "type": "date"}, {"key": "bill", "label": "Bill #", "type": "text"}, {"key": "po", "label": "PO #", "type": "text"}, {"key": "vendor", "label": "Vendor", "type": "text"}, {"key": "amount", "label": "Amount (₹)", "type": "currency"}, {"key": "dueDate", "label": "Due Date", "type": "date"}, {"key": "status", "label": "Status", "type": "text"}]}'::jsonb,
  '{"rows": [{"date": "2026-08-30", "bill": "VB-901", "po": "PO/2026/008", "vendor": "Asian Paints Industrial", "amount": "34500.00", "dueDate": "2026-09-15", "status": "Approved"}]}'::jsonb,
  'Total Approved Liabilities = SUM(Approved Bills)',
  NULL
),
(
  'Vendor Payment Tracker',
  'vendor-payment-tracker',
  (SELECT id FROM template_categories WHERE slug = 'purchase'),
  'Accounts Payable, Cashiers',
  'Track vendor bill settlements, cheque clearing, bank references, TDS deductions, and net disbursed amounts.',
  'XLSX / CSV / PDF',
  '1.0.0',
  'Standard Business Format — Original',
  'Open Business Format — Free for commercial & operational use',
  '["Payment Date", "Voucher #", "Vendor", "Bill #", "Gross Payable (₹)", "TDS Deducted (₹)", "Net Paid (₹)", "Bank UTR #"]'::jsonb,
  '{"columns": [{"key": "date", "label": "Date", "type": "date"}, {"key": "voucher", "label": "Voucher #", "type": "text"}, {"key": "vendor", "label": "Vendor", "type": "text"}, {"key": "bill", "label": "Bill #", "type": "text"}, {"key": "gross", "label": "Gross Payable (₹)", "type": "currency"}, {"key": "tds", "label": "TDS (₹)", "type": "currency"}, {"key": "net", "label": "Net Paid (₹)", "type": "formula", "formula": "Gross - TDS"}, {"key": "utr", "label": "UTR #", "type": "text"}]}'::jsonb,
  '{"rows": [{"date": "2026-09-02", "voucher": "VP-054", "vendor": "Timber Craft", "bill": "BILL/2026/001", "gross": "40000.00", "tds": "800.00", "net": "39200.00", "utr": "SBIN0048192"}]}'::jsonb,
  'Net Paid = Gross Payable - TDS Deducted',
  NULL
),
(
  'Vendor Comparison Sheet',
  'vendor-comparison-sheet',
  (SELECT id FROM template_categories WHERE slug = 'purchase'),
  'Procurement Executives, Estimators',
  'Comparative matrix comparing multiple supplier quotes side-by-side on rate, quality, delivery time, and credit terms.',
  'XLSX / CSV / PDF',
  '1.0.0',
  'Standard Business Format — Original',
  'Open Business Format — Free for commercial & operational use',
  '["Item", "Required Qty", "Vendor A Rate (₹)", "Vendor B Rate (₹)", "Vendor C Rate (₹)", "Selected Vendor", "Cost Saving (₹)"]'::jsonb,
  '{"columns": [{"key": "item", "label": "Item", "type": "text"}, {"key": "qty", "label": "Qty", "type": "number"}, {"key": "vendorA", "label": "Vendor A Rate (₹)", "type": "currency"}, {"key": "vendorB", "label": "Vendor B Rate (₹)", "type": "currency"}, {"key": "vendorC", "label": "Vendor C Rate (₹)", "type": "currency"}, {"key": "selected", "label": "Selected Vendor", "type": "text"}, {"key": "saving", "label": "Cost Saving (₹)", "type": "formula"}]}'::jsonb,
  '{"rows": [{"item": "Soft-Close Drawer Channels (18 in)", "qty": 100, "vendorA": "380.00", "vendorB": "345.00", "vendorC": "390.00", "selected": "Vendor B (Ozone)", "saving": "4500.00"}]}'::jsonb,
  'Cost Saving = (Highest Quote - Selected Quote) * Quantity',
  NULL
),

-- ------------------------------------------------------------
-- INVENTORY
-- ------------------------------------------------------------
(
  'Stock Register',
  'stock-register',
  (SELECT id FROM template_categories WHERE slug = 'inventory'),
  'Warehouse Managers, Storekeepers, Retailers',
  'Track current stock balances, minimum order levels, unit costs, and total inventory value across all warehouses.',
  'XLSX / CSV / PDF',
  '1.0.0',
  'Urban Furniture ERP — Original Template',
  'Open Business Format — Free for commercial & operational use',
  '["Product SKU", "Product Name", "Category", "Unit Cost (₹)", "Stock on Hand", "Reorder Level", "Total Stock Value (₹)"]'::jsonb,
  '{"columns": [{"key": "sku", "label": "SKU", "type": "text"}, {"key": "name", "label": "Product Name", "type": "text"}, {"key": "category", "label": "Category", "type": "text"}, {"key": "cost", "label": "Unit Cost (₹)", "type": "currency"}, {"key": "stock", "label": "Stock on Hand", "type": "number"}, {"key": "reorder", "label": "Reorder Level", "type": "number"}, {"key": "value", "label": "Stock Value (₹)", "type": "formula", "formula": "Unit Cost * Stock on Hand"}]}'::jsonb,
  '{"rows": [{"sku": "CH-OAK-01", "name": "Oak Wood Dining Chair", "category": "Chairs", "cost": "3200.00", "stock": 24, "reorder": 6, "value": "76800.00"}, {"sku": "TB-WAL-02", "name": "Walnut Study Table", "category": "Tables", "cost": "8500.00", "stock": 10, "reorder": 3, "value": "85000.00"}]}'::jsonb,
  'Total Stock Value = Unit Cost * Stock on Hand',
  'stock_on_hand'
),
(
  'Stock In/Out Register',
  'stock-in-out-register',
  (SELECT id FROM template_categories WHERE slug = 'inventory'),
  'Storekeepers, Dispatch Officers',
  'Daily stock movements log tracking receipts from suppliers (In) and dispatches to customer orders (Out).',
  'XLSX / CSV / PDF',
  '1.0.0',
  'Standard Business Format — Original',
  'Open Business Format — Free for commercial & operational use',
  '["Date", "Product SKU", "Movement Type", "Ref Doc (PO/SO)", "Quantity In", "Quantity Out", "Cumulative Stock"]'::jsonb,
  '{"columns": [{"key": "date", "label": "Date", "type": "date"}, {"key": "sku", "label": "SKU", "type": "text"}, {"key": "type", "label": "Type", "type": "text"}, {"key": "doc", "label": "Ref Doc", "type": "text"}, {"key": "inQty", "label": "Qty In", "type": "number"}, {"key": "outQty", "label": "Qty Out", "type": "number"}, {"key": "balance", "label": "Balance", "type": "formula"}]}'::jsonb,
  '{"openingBalance": "50", "rows": [{"date": "2026-09-01", "sku": "CH-OAK-01", "type": "Purchase Receipt", "doc": "PO-041", "inQty": 20, "outQty": 0, "balance": 70}, {"date": "2026-09-02", "sku": "CH-OAK-01", "type": "Sales Delivery", "doc": "SO-108", "inQty": 0, "outQty": 8, "balance": 62}]}'::jsonb,
  'Closing Stock = Opening Stock + SUM(Qty In) - SUM(Qty Out)',
  NULL
),
(
  'Inventory Valuation Sheet',
  'inventory-valuation-sheet',
  (SELECT id FROM template_categories WHERE slug = 'inventory'),
  'Accountants, Cost Auditors',
  'Periodic inventory valuation by FIFO / Weighted Average method for balance sheet and tax reporting.',
  'XLSX / CSV / PDF',
  '1.0.0',
  'Standard Business Format — Original',
  'Open Business Format — Free for commercial & operational use',
  '["Item Code", "Description", "UOM", "Quantity", "Average Cost (₹)", "Selling Price (₹)", "Total Asset Value (₹)"]'::jsonb,
  '{"columns": [{"key": "code", "label": "Item Code", "type": "text"}, {"key": "desc", "label": "Description", "type": "text"}, {"key": "uom", "label": "UOM", "type": "text"}, {"key": "qty", "label": "Quantity", "type": "number"}, {"key": "cost", "label": "Avg Cost (₹)", "type": "currency"}, {"key": "price", "label": "Selling Price (₹)", "type": "currency"}, {"key": "value", "label": "Total Asset Value (₹)", "type": "formula", "formula": "Qty * Avg Cost"}]}'::jsonb,
  '{"rows": [{"code": "SF-LEA-03", "name": "3-Seater Leather Sofa", "uom": "PCS", "qty": 6, "cost": "28000.00", "price": "48000.00", "value": "168000.00"}]}'::jsonb,
  'Total Asset Value = Quantity * Average Unit Cost',
  NULL
),
(
  'Low Stock Tracker',
  'low-stock-tracker',
  (SELECT id FROM template_categories WHERE slug = 'inventory'),
  'Store Managers, Purchasing Clerks',
  'Critical inventory alerts for items reaching or falling below safety stock to prevent production stoppages.',
  'XLSX / CSV / PDF',
  '1.0.0',
  'Standard Business Format — Original',
  'Open Business Format — Free for commercial & operational use',
  '["SKU", "Item Description", "Current Stock", "Reorder Level", "Deficit / Shortfall", "Preferred Supplier", "Lead Time (Days)"]'::jsonb,
  '{"columns": [{"key": "sku", "label": "SKU", "type": "text"}, {"key": "item", "label": "Item", "type": "text"}, {"key": "stock", "label": "Current Stock", "type": "number"}, {"key": "reorder", "label": "Reorder Level", "type": "number"}, {"key": "shortfall", "label": "Shortfall", "type": "formula", "formula": "MAX(0, Reorder - Stock)"}, {"key": "supplier", "label": "Supplier", "type": "text"}, {"key": "leadTime", "label": "Lead Time", "type": "number"}]}'::jsonb,
  '{"rows": [{"sku": "GL-ADH-01", "item": "Polyurethane Wood Adhesive (5kg)", "stock": 2, "reorder": 8, "shortfall": 6, "supplier": "Pidilite Industrial", "leadTime": 2}]}'::jsonb,
  'Shortfall = MAX(0, Reorder Level - Current Stock)',
  NULL
),
(
  'Product Master',
  'product-master',
  (SELECT id FROM template_categories WHERE slug = 'inventory'),
  'Catalogue Managers, Data Administrators',
  'Centralized directory of all products, SKUs, dimensions, material compositions, tax codes, and pricing rules.',
  'XLSX / CSV / PDF',
  '1.0.0',
  'Standard Business Format — Original',
  'Open Business Format — Free for commercial & operational use',
  '["SKU", "Product Title", "Type", "HSN Code", "Cost (₹)", "Selling Price (₹)", "GST %", "Gross Margin (%)"]'::jsonb,
  '{"columns": [{"key": "sku", "label": "SKU", "type": "text"}, {"key": "title", "label": "Title", "type": "text"}, {"key": "type", "label": "Type", "type": "text"}, {"key": "hsn", "label": "HSN", "type": "text"}, {"key": "cost", "label": "Cost (₹)", "type": "currency"}, {"key": "price", "label": "Price (₹)", "type": "currency"}, {"key": "gst", "label": "GST %", "type": "number"}, {"key": "margin", "label": "Margin %", "type": "formula", "formula": "(Price - Cost) / Price * 100"}]}'::jsonb,
  '{"rows": [{"sku": "BD-KNG-01", "title": "King Size Solid Teak Bed", "type": "goods", "hsn": "9403", "cost": "24000.00", "price": "42000.00", "gst": 18, "margin": 42.86}]}'::jsonb,
  'Margin % = ((Selling Price - Cost Price) / Selling Price) * 100',
  NULL
),
(
  'Purchase vs Sales Stock Report',
  'purchase-vs-sales-stock-report',
  (SELECT id FROM template_categories WHERE slug = 'inventory'),
  'Business Analysts, Inventory Controllers',
  'Reconcile total units purchased, units sold, and expected closing inventory to identify shrinkage and wastage.',
  'XLSX / CSV / PDF',
  '1.0.0',
  'Standard Business Format — Original',
  'Open Business Format — Free for commercial & operational use',
  '["SKU", "Product Name", "Opening Qty", "Units Purchased", "Units Sold", "Expected Balance", "Physical Count", "Variance"]'::jsonb,
  '{"columns": [{"key": "sku", "label": "SKU", "type": "text"}, {"key": "name", "label": "Product", "type": "text"}, {"key": "opening", "label": "Opening", "type": "number"}, {"key": "purchased", "label": "Purchased", "type": "number"}, {"key": "sold", "label": "Sold", "type": "number"}, {"key": "expected", "label": "Expected", "type": "formula", "formula": "Opening + Purchased - Sold"}, {"key": "physical", "label": "Physical Count", "type": "number"}, {"key": "variance", "label": "Variance", "type": "formula", "formula": "Physical - Expected"}]}'::jsonb,
  '{"rows": [{"sku": "CH-OAK-01", "name": "Oak Dining Chair", "opening": 15, "purchased": 30, "sold": 22, "expected": 23, "physical": 23, "variance": 0}]}'::jsonb,
  'Expected = Opening + Purchased - Sold; Variance = Physical - Expected',
  NULL
),

-- ------------------------------------------------------------
-- INDUSTRY-SPECIFIC: CONTRACTOR
-- ------------------------------------------------------------
(
  'Project Cost Sheet',
  'contractor-project-cost-sheet',
  (SELECT id FROM template_categories WHERE slug = 'industry-specific'),
  'Contractors, Civil Engineers, Interior Fit-out',
  'Complete cost estimation sheet for contractor projects breaking down materials, labour, equipment, and profit margins.',
  'XLSX / CSV / PDF',
  '1.0.0',
  'Standard Business Format — Original',
  'Open Business Format — Free for commercial & operational use',
  '["Cost Element", "Description", "Estimated Cost (₹)", "Actual Cost Incurred (₹)", "Variance (₹)", "Status"]'::jsonb,
  '{"columns": [{"key": "element", "label": "Cost Element", "type": "text"}, {"key": "desc", "label": "Description", "type": "text"}, {"key": "budget", "label": "Budget (₹)", "type": "currency"}, {"key": "actual", "label": "Actual (₹)", "type": "currency"}, {"key": "variance", "label": "Variance (₹)", "type": "formula", "formula": "Budget - Actual"}, {"key": "status", "label": "Status", "type": "text"}]}'::jsonb,
  '{"budget": "500000.00", "rows": [{"element": "Raw Materials", "desc": "Plywood, laminates, hardware, veneer", "budget": "240000.00", "actual": "232000.00", "variance": "8000.00", "status": "Under Budget"}, {"element": "Direct Labour", "desc": "Carpentry, polishing, installation crew", "budget": "140000.00", "actual": "145000.00", "variance": "-5000.00", "status": "Overrun"}, {"element": "Site Overheads & Transport", "desc": "Freight, permits, scaffolding", "budget": "40000.00", "actual": "38000.00", "variance": "2000.00", "status": "Under Budget"}, {"element": "Contractor Margin (15%)", "desc": "Project net profit allowance", "budget": "80000.00", "actual": "85000.00", "variance": "5000.00", "status": "Realized"}]}'::jsonb,
  'Total Project Cost = Materials + Labour + Overheads; Net Margin = Contract Price - Total Cost',
  NULL
),
(
  'Material Consumption Sheet',
  'contractor-material-consumption-sheet',
  (SELECT id FROM template_categories WHERE slug = 'industry-specific'),
  'Site Supervisors, Civil Contractors',
  'Track raw material requisition, site deliveries, actual consumption per floor/phase, and balance on site.',
  'XLSX / CSV / PDF',
  '1.0.0',
  'Standard Business Format — Original',
  'Open Business Format — Free for commercial & operational use',
  '["Material", "Unit", "Received on Site", "Consumed This Week", "Wastage Qty", "Balance on Site"]'::jsonb,
  '{"columns": [{"key": "material", "label": "Material", "type": "text"}, {"key": "unit", "label": "Unit", "type": "text"}, {"key": "received", "label": "Received", "type": "number"}, {"key": "consumed", "label": "Consumed", "type": "number"}, {"key": "waste", "label": "Wastage", "type": "number"}, {"key": "balance", "label": "Balance", "type": "formula", "formula": "Received - Consumed - Waste"}]}'::jsonb,
  '{"rows": [{"material": "Cement Bags (Grade 53)", "unit": "Bags", "received": 200, "consumed": 140, "waste": 2, "balance": 58}, {"material": "Steel Rebars (12mm)", "unit": "Tons", "received": 5, "consumed": 3.8, "waste": 0.1, "balance": 1.1}]}'::jsonb,
  'Balance on Site = Received - Consumed - Wastage',
  NULL
),
(
  'Labour Cost Sheet',
  'contractor-labour-cost-sheet',
  (SELECT id FROM template_categories WHERE slug = 'industry-specific'),
  'Site Contractors, Labour Contractors',
  'Daily and weekly labour wage calculation tracking skilled, semi-skilled, and unskilled workers, overtime, and advances.',
  'XLSX / CSV / PDF',
  '1.0.0',
  'Standard Business Format — Original',
  'Open Business Format — Free for commercial & operational use',
  '["Worker Name", "Trade / Skill", "Days Worked", "Daily Wage (₹)", "OT Hours", "OT Rate (₹)", "Advance (₹)", "Net Payable (₹)"]'::jsonb,
  '{"columns": [{"key": "name", "label": "Worker Name", "type": "text"}, {"key": "skill", "label": "Skill", "type": "text"}, {"key": "days", "label": "Days", "type": "number"}, {"key": "wage", "label": "Daily Wage (₹)", "type": "currency"}, {"key": "otHours", "label": "OT Hours", "type": "number"}, {"key": "otRate", "label": "OT Rate (₹)", "type": "currency"}, {"key": "advance", "label": "Advance (₹)", "type": "currency"}, {"key": "net", "label": "Net Payable (₹)", "type": "formula", "formula": "(Days * Wage) + (OT Hours * OT Rate) - Advance"}]}'::jsonb,
  '{"rows": [{"name": "Ramesh Carpenter", "skill": "Master Craftsman", "days": 6, "wage": "1200.00", "otHours": 8, "otRate": "200.00", "advance": "1500.00", "net": "7300.00"}]}'::jsonb,
  'Net Payable = (Days * Daily Wage) + (OT Hours * OT Rate) - Advance Deductions',
  NULL
),
(
  'Contractor Payment Tracker',
  'contractor-payment-tracker',
  (SELECT id FROM template_categories WHERE slug = 'industry-specific'),
  'General Contractors, Subcontractors',
  'Track running account (RA) bills submitted to clients, retention money withheld, TDS deductions, and net disbursements.',
  'XLSX / CSV / PDF',
  '1.0.0',
  'Standard Business Format — Original',
  'Open Business Format — Free for commercial & operational use',
  '["RA Bill #", "Date Submitted", "Gross Amount (₹)", "Retention (5%) (₹)", "TDS (2%) (₹)", "Net Certified (₹)", "Payment Received (₹)", "Pending (₹)"]'::jsonb,
  '{"columns": [{"key": "ra", "label": "RA Bill #", "type": "text"}, {"key": "date", "label": "Date", "type": "date"}, {"key": "gross", "label": "Gross Amount (₹)", "type": "currency"}, {"key": "retention", "label": "Retention (₹)", "type": "formula", "formula": "Gross * 0.05"}, {"key": "tds", "label": "TDS (₹)", "type": "formula", "formula": "Gross * 0.02"}, {"key": "net", "label": "Net Certified (₹)", "type": "formula", "formula": "Gross - Retention - TDS"}, {"key": "received", "label": "Received (₹)", "type": "currency"}, {"key": "pending", "label": "Pending (₹)", "type": "formula", "formula": "Net Certified - Received"}]}'::jsonb,
  '{"rows": [{"ra": "RA-01", "date": "2026-08-15", "gross": "250000.00", "retention": "12500.00", "tds": "5000.00", "net": "232500.00", "received": "232500.00", "pending": "0.00"}]}'::jsonb,
  'Net Certified = Gross - Retention (5%) - TDS (2%); Pending = Net Certified - Received',
  NULL
),
(
  'Project Billing Tracker',
  'contractor-project-billing-tracker',
  (SELECT id FROM template_categories WHERE slug = 'industry-specific'),
  'Project Engineers, Quantity Surveyors',
  'Monitor milestones, milestone percentages, billed amounts, cumulative billing against total contract value.',
  'XLSX / CSV / PDF',
  '1.0.0',
  'Standard Business Format — Original',
  'Open Business Format — Free for commercial & operational use',
  '["Milestone", "Target Completion", "% of Total", "Milestone Value (₹)", "Invoice #", "Billed Date", "Payment Status"]'::jsonb,
  '{"columns": [{"key": "milestone", "label": "Milestone", "type": "text"}, {"key": "target", "label": "Target Date", "type": "date"}, {"key": "pct", "label": "% Contract", "type": "number"}, {"key": "value", "label": "Milestone Value (₹)", "type": "currency"}, {"key": "invoice", "label": "Invoice #", "type": "text"}, {"key": "billedDate", "label": "Billed Date", "type": "date"}, {"key": "status", "label": "Status", "type": "text"}]}'::jsonb,
  '{"rows": [{"milestone": "Mobilization & Material Procurement", "target": "2026-08-10", "pct": 20, "value": "100000.00", "invoice": "INV/2026/010", "billedDate": "2026-08-10", "status": "Paid"}, {"milestone": "Carcass & Structure Assembly", "target": "2026-08-30", "pct": 40, "value": "200000.00", "invoice": "INV/2026/015", "billedDate": "2026-08-30", "status": "Paid"}]}'::jsonb,
  'Cumulative Billed % = SUM(Billed Milestone Percentages)',
  NULL
),

-- ------------------------------------------------------------
-- INDUSTRY-SPECIFIC: FURNITURE BUSINESS
-- ------------------------------------------------------------
(
  'Furniture Product Catalogue',
  'furniture-product-catalogue',
  (SELECT id FROM template_categories WHERE slug = 'industry-specific'),
  'Furniture Showrooms, Furniture Manufacturers',
  'Showroom product catalog with dimensions, wood type (Teak, Sheesham, Oak), fabric finish, warranty, and MRP.',
  'XLSX / CSV / PDF',
  '1.0.0',
  'Urban Furniture ERP — Original Template',
  'Open Business Format — Free for commercial & operational use',
  '["Model Code", "Item Name", "Wood / Material", "Dimensions (L x W x H)", "Finish", "Warranty", "Retail Price (₹)"]'::jsonb,
  '{"columns": [{"key": "code", "label": "Model Code", "type": "text"}, {"key": "name", "label": "Item Name", "type": "text"}, {"key": "material", "label": "Material", "type": "text"}, {"key": "dim", "label": "Dimensions", "type": "text"}, {"key": "finish", "label": "Finish", "type": "text"}, {"key": "warranty", "label": "Warranty", "type": "text"}, {"key": "price", "label": "Price (₹)", "type": "currency"}]}'::jsonb,
  '{"rows": [{"code": "UF-BED-001", "name": "Royale King Storage Bed", "material": "Solid Teak Wood", "dim": "78 x 72 x 45 in", "finish": "Walnut Matte", "warranty": "5 Years", "price": "48500.00"}, {"code": "UF-SOF-003", "name": "Milano Chesterfield 3-Seater", "material": "Pinewood & Velvet", "dim": "84 x 36 x 32 in", "finish": "Emerald Velvet", "warranty": "3 Years", "price": "42000.00"}]}'::jsonb,
  'Official Showroom List Price',
  NULL
),
(
  'Furniture Stock Register',
  'furniture-stock-register',
  (SELECT id FROM template_categories WHERE slug = 'industry-specific'),
  'Furniture Showrooms, Warehouse Managers',
  'Specialized inventory tracker for furniture pieces categorized into Living Room, Bedroom, Dining, and Office.',
  'XLSX / CSV / PDF',
  '1.0.0',
  'Urban Furniture ERP — Original Template',
  'Open Business Format — Free for commercial & operational use',
  '["SKU", "Furniture Item", "Room Category", "Showroom Display Qty", "Warehouse Qty", "Total Available", "Unit Cost (₹)", "Total Inventory Value (₹)"]'::jsonb,
  '{"columns": [{"key": "sku", "label": "SKU", "type": "text"}, {"key": "item", "label": "Item", "type": "text"}, {"key": "room", "label": "Room", "type": "text"}, {"key": "display", "label": "Display Qty", "type": "number"}, {"key": "warehouse", "label": "Warehouse Qty", "type": "number"}, {"key": "totalQty", "label": "Total Qty", "type": "formula", "formula": "Display + Warehouse"}, {"key": "cost", "label": "Unit Cost (₹)", "type": "currency"}, {"key": "val", "label": "Total Value (₹)", "type": "formula", "formula": "Total Qty * Unit Cost"}]}'::jsonb,
  '{"rows": [{"sku": "UF-DIN-006", "name": "Marble Top 6-Seater Dining Set", "room": "Dining", "display": 1, "warehouse": 4, "totalQty": 5, "cost": "32000.00", "val": "160000.00"}]}'::jsonb,
  'Total Qty = Display + Warehouse; Total Value = Total Qty * Unit Cost',
  NULL
),
(
  'Custom Furniture Order Sheet',
  'custom-furniture-order-sheet',
  (SELECT id FROM template_categories WHERE slug = 'industry-specific'),
  'Custom Furniture Makers, Interior Carpenters',
  'Order intake sheet capturing custom client measurements, wood species, upholstery swatch codes, hardware brands, and advances.',
  'XLSX / CSV / PDF',
  '1.0.0',
  'Urban Furniture ERP — Original Template',
  'Open Business Format — Free for commercial & operational use',
  '["Order Ref", "Customer Name", "Furniture Piece", "Custom Dimensions", "Wood Grade", "Fabric Swatch", "Agreed Price (₹)", "Advance Paid (₹)", "Delivery Due Date"]'::jsonb,
  '{"columns": [{"key": "ref", "label": "Order Ref", "type": "text"}, {"key": "customer", "label": "Customer", "type": "text"}, {"key": "piece", "label": "Piece", "type": "text"}, {"key": "dim", "label": "Dimensions", "type": "text"}, {"key": "wood", "label": "Wood Grade", "type": "text"}, {"key": "fabric", "label": "Fabric Swatch", "type": "text"}, {"key": "price", "label": "Price (₹)", "type": "currency"}, {"key": "advance", "label": "Advance (₹)", "type": "currency"}, {"key": "dueDate", "label": "Due Date", "type": "date"}]}'::jsonb,
  '{"rows": [{"ref": "CUST-089", "customer": "Vikram Singhania", "piece": "L-Shape Sectional Sofa", "dim": "10 x 8 ft", "wood": "Kiln-dried Salwood", "fabric": "Sarom Slate Grey #402", "price": "75000.00", "advance": "40000.00", "dueDate": "2026-09-25"}]}'::jsonb,
  'Balance Due at Delivery = Agreed Price - Advance Paid',
  NULL
),
(
  'Furniture Production Cost Sheet',
  'furniture-production-cost-sheet',
  (SELECT id FROM template_categories WHERE slug = 'industry-specific'),
  'Furniture Manufacturers, Factory Managers',
  'Detailed Bill of Materials (BOM) & production cost calculator combining timber, hardware, foam, polishing, and artisan labour.',
  'XLSX / CSV / PDF',
  '1.0.0',
  'Urban Furniture ERP — Original Template',
  'Open Business Format — Free for commercial & operational use',
  '["Cost Head", "Description", "Material / Resource", "Quantity", "Rate (₹)", "Subtotal (₹)"]'::jsonb,
  '{"columns": [{"key": "head", "label": "Cost Head", "type": "text"}, {"key": "desc", "label": "Description", "type": "text"}, {"key": "res", "label": "Resource", "type": "text"}, {"key": "qty", "label": "Quantity", "type": "number"}, {"key": "rate", "label": "Rate (₹)", "type": "currency"}, {"key": "subtotal", "label": "Subtotal (₹)", "type": "formula", "formula": "Qty * Rate"}]}'::jsonb,
  '{"rows": [{"head": "Timber (Wood)", "desc": "Carcass & Legs", "res": "CP Teak (CFT)", "qty": 8, "rate": "2800.00", "subtotal": "22400.00"}, {"head": "Hardware", "desc": "Handles & Hinges", "res": "Hettich Soft-Close", "qty": 1, "rate": "3500.00", "subtotal": "3500.00"}, {"head": "Polishing", "desc": "PU Matt Lacquer finish", "res": "Milesi PU", "qty": 1, "rate": "4200.00", "subtotal": "4200.00"}, {"head": "Artisan Labour", "desc": "Carpentry & Joinery", "res": "Artisan Hours", "qty": 28, "rate": "250.00", "subtotal": "7000.00"}]}'::jsonb,
  'Total Unit Manufacturing Cost = Timber + Hardware + Polish + Labour + 10% Factory Overhead',
  NULL
),
(
  'Furniture Job Card',
  'furniture-job-card',
  (SELECT id FROM template_categories WHERE slug = 'industry-specific'),
  'Factory Foremen, Woodworking Carpenters',
  'Shop-floor manufacturing job card tracking item cutting, machining, joinery, sanding, polishing, and upholstery stages.',
  'XLSX / CSV / PDF',
  '1.0.0',
  'Urban Furniture ERP — Original Template',
  'Open Business Format — Free for commercial & operational use',
  '["Job #", "Item", "Woodworking Stage", "Assigned Artisan", "Start Date", "Target Completion", "Quality Check (QC)"]'::jsonb,
  '{"columns": [{"key": "job", "label": "Job #", "type": "text"}, {"key": "item", "label": "Item", "type": "text"}, {"key": "stage", "label": "Stage", "type": "text"}, {"key": "artisan", "label": "Artisan", "type": "text"}, {"key": "start", "label": "Start Date", "type": "date"}, {"key": "target", "label": "Target", "type": "date"}, {"key": "qc", "label": "QC Status", "type": "text"}]}'::jsonb,
  '{"rows": [{"job": "JOB-104", "item": "Teak Dining Table", "stage": "Final PU Polish Coating", "artisan": "Surendra", "start": "2026-09-02", "target": "2026-09-05", "qc": "Passed inspection"}]}'::jsonb,
  'Track completion of all 5 production stages before dispatch authorization.',
  NULL
),
(
  'Furniture Delivery Tracker',
  'furniture-delivery-tracker',
  (SELECT id FROM template_categories WHERE slug = 'industry-specific'),
  'Logistics Supervisors, Delivery Drivers',
  'Track outbound showroom and custom furniture deliveries, delivery vehicles, driver contacts, customer sign-offs, and COD collections.',
  'XLSX / CSV / PDF',
  '1.0.0',
  'Urban Furniture ERP — Original Template',
  'Open Business Format — Free for commercial & operational use',
  '["Delivery Date", "Dispatch Challan #", "Customer Name", "Delivery Address", "Driver Name", "Vehicle No", "COD Amount (₹)", "Delivery Status"]'::jsonb,
  '{"columns": [{"key": "date", "label": "Date", "type": "date"}, {"key": "challan", "label": "Challan #", "type": "text"}, {"key": "customer", "label": "Customer", "type": "text"}, {"key": "address", "label": "Address", "type": "text"}, {"key": "driver", "label": "Driver", "type": "text"}, {"key": "vehicle", "label": "Vehicle #", "type": "text"}, {"key": "cod", "label": "COD Amount (₹)", "type": "currency"}, {"key": "status", "label": "Status", "type": "text"}]}'::jsonb,
  '{"rows": [{"date": "2026-09-04", "challan": "DC-049", "customer": "Ananya Sharma", "address": "B-402 Palm Heights, Mumbai", "driver": "Iqbal Khan", "vehicle": "MH-04-AB-1290", "cod": "15000.00", "status": "Delivered & Collected"}]}'::jsonb,
  'Daily Cash on Delivery = SUM(COD Collected by Driver)',
  NULL
),

-- ------------------------------------------------------------
-- INDUSTRY-SPECIFIC: FREELANCER
-- ------------------------------------------------------------
(
  'Freelance Client Register',
  'freelance-client-register',
  (SELECT id FROM template_categories WHERE slug = 'personal-business'),
  'Freelancers, Digital Designers, Consultants',
  'Master client directory tracking client companies, contact details, hourly vs fixed billing models, and active retainers.',
  'XLSX / CSV / PDF',
  '1.0.0',
  'Standard Business Format — Original',
  'Open Business Format — Free for commercial & operational use',
  '["Client Name", "Contact Person", "Email", "Phone", "Billing Model", "Standard Rate (₹)", "Active Projects", "Total Billed YTD (₹)"]'::jsonb,
  '{"columns": [{"key": "client", "label": "Client", "type": "text"}, {"key": "contact", "label": "Contact Person", "type": "text"}, {"key": "email", "label": "Email", "type": "text"}, {"key": "phone", "label": "Phone", "type": "text"}, {"key": "model", "label": "Model", "type": "text"}, {"key": "rate", "label": "Rate (₹)", "type": "currency"}, {"key": "projects", "label": "Projects", "type": "number"}, {"key": "billed", "label": "Billed YTD (₹)", "type": "currency"}]}'::jsonb,
  '{"rows": [{"client": "Urban Edge Studios", "contact": "Meera Patel", "email": "meera@urbanedge.com", "phone": "+91 98200 11223", "model": "Retainer", "rate": "45000.00", "projects": 2, "billed": "135000.00"}]}'::jsonb,
  'Total Client Portfolio Value = SUM(Billed YTD)',
  NULL
),
(
  'Freelance Project Tracker',
  'freelance-project-tracker',
  (SELECT id FROM template_categories WHERE slug = 'personal-business'),
  'Freelance Designers, Developers, Consultants',
  'Track client deliverables, committed scope, billable hours spent, milestone deadlines, and completion percentages.',
  'XLSX / CSV / PDF',
  '1.0.0',
  'Standard Business Format — Original',
  'Open Business Format — Free for commercial & operational use',
  '["Project Title", "Client", "Scope Summary", "Contract Value (₹)", "Hours Logged", "Deadline", "Progress (%)", "Status"]'::jsonb,
  '{"columns": [{"key": "title", "label": "Project Title", "type": "text"}, {"key": "client", "label": "Client", "type": "text"}, {"key": "scope", "label": "Scope", "type": "text"}, {"key": "value", "label": "Contract (₹)", "type": "currency"}, {"key": "hours", "label": "Hours Logged", "type": "number"}, {"key": "deadline", "label": "Deadline", "type": "date"}, {"key": "progress", "label": "Progress %", "type": "number"}, {"key": "status", "label": "Status", "type": "text"}]}'::jsonb,
  '{"rows": [{"title": "3D Furniture Model Rendering Package", "client": "Heritage Living", "scope": "15 high-poly 3D showroom models", "value": "60000.00", "hours": 32, "deadline": "2026-09-15", "progress": 70, "status": "In Progress"}]}'::jsonb,
  'Effective Hourly Rate = Contract Value / Total Hours Logged',
  NULL
),
(
  'Freelance Payment Due Tracker',
  'freelance-payment-due-tracker',
  (SELECT id FROM template_categories WHERE slug = 'personal-business'),
  'Freelancers, Solo Creators',
  'Track freelance invoices sent, payment due dates, overdue reminder schedules, and pending bank transfers.',
  'XLSX / CSV / PDF',
  '1.0.0',
  'Standard Business Format — Original',
  'Open Business Format — Free for commercial & operational use',
  '["Invoice #", "Client Name", "Invoice Date", "Amount (₹)", "Payment Due Date", "Overdue Days", "Reminder Status"]'::jsonb,
  '{"columns": [{"key": "inv", "label": "Invoice #", "type": "text"}, {"key": "client", "label": "Client", "type": "text"}, {"key": "date", "label": "Invoice Date", "type": "date"}, {"key": "amount", "label": "Amount (₹)", "type": "currency"}, {"key": "due", "label": "Due Date", "type": "date"}, {"key": "days", "label": "Days Overdue", "type": "formula", "formula": "MAX(0, Today - Due Date)"}, {"key": "status", "label": "Status", "type": "text"}]}'::jsonb,
  '{"rows": [{"inv": "INV-FL-08", "client": "Apex Interior Design", "date": "2026-08-20", "amount": "25000.00", "due": "2026-09-04", "days": 2, "status": "Reminder 1 Sent"}]}'::jsonb,
  'Total Pending Receivables = SUM(Outstanding Invoices)',
  NULL
),

-- ------------------------------------------------------------
-- INDUSTRY-SPECIFIC: RETAIL
-- ------------------------------------------------------------
(
  'Retail Daily Sales Register',
  'retail-daily-sales-register',
  (SELECT id FROM template_categories WHERE slug = 'industry-specific'),
  'Retail Stores, Boutiques, Showrooms, Hardware Shops',
  'Log daily retail cash register sales, credit card swipes, UPI QR scans, and compute end-of-day register reconciliation.',
  'XLSX / CSV / PDF',
  '1.0.0',
  'Standard Business Format — Original',
  'Open Business Format — Free for commercial & operational use',
  '["Time", "Bill / Receipt #", "Items Sold", "Cash (₹)", "Card (₹)", "UPI (₹)", "Total Sale (₹)"]'::jsonb,
  '{"columns": [{"key": "time", "label": "Time", "type": "text"}, {"key": "bill", "label": "Receipt #", "type": "text"}, {"key": "items", "label": "Items Sold", "type": "text"}, {"key": "cash", "label": "Cash (₹)", "type": "currency"}, {"key": "card", "label": "Card (₹)", "type": "currency"}, {"key": "upi", "label": "UPI (₹)", "type": "currency"}, {"key": "total", "label": "Total (₹)", "type": "formula", "formula": "Cash + Card + UPI"}]}'::jsonb,
  '{"rows": [{"time": "11:30 AM", "bill": "POS-001", "items": "Wooden Coasters Set (x2)", "cash": "0.00", "card": "1200.00", "upi": "0.00", "total": "1200.00"}, {"time": "02:15 PM", "bill": "POS-002", "items": "Velvet Cushion Covers (x4)", "cash": "1800.00", "card": "0.00", "upi": "0.00", "total": "1800.00"}, {"time": "04:45 PM", "bill": "POS-003", "items": "Accent Lamp", "cash": "0.00", "card": "0.00", "upi": "3500.00", "total": "3500.00"}]}'::jsonb,
  'Total Day Sales = SUM(Cash) + SUM(Card) + SUM(UPI)',
  NULL
),
(
  'Customer Credit Register (Udhar Khata)',
  'customer-credit-register',
  (SELECT id FROM template_categories WHERE slug = 'industry-specific'),
  'Kirana, Retail Shops, Local Hardware Stores',
  'Traditional customer credit register tracking item purchases on trust/credit, repayments, and outstanding balances.',
  'XLSX / CSV / PDF',
  '1.0.0',
  'Standard Business Format — Original',
  'Open Business Format — Free for commercial & operational use',
  '["Date", "Customer Name", "Phone", "Items Purchased", "Credit Given (Debit ₹)", "Repayment Received (Credit ₹)", "Current Due Balance (₹)"]'::jsonb,
  '{"columns": [{"key": "date", "label": "Date", "type": "date"}, {"key": "customer", "label": "Customer", "type": "text"}, {"key": "phone", "label": "Phone", "type": "text"}, {"key": "items", "label": "Items", "type": "text"}, {"key": "debit", "label": "Credit Given (₹)", "type": "currency"}, {"key": "credit", "label": "Repayment (₹)", "type": "currency"}, {"key": "balance", "label": "Current Due (₹)", "type": "formula"}]}'::jsonb,
  '{"rows": [{"date": "2026-09-01", "customer": "Sunil Varma", "phone": "+91 99302 44556", "items": "Curtain Rods & Screws", "debit": "3400.00", "credit": "0.00", "balance": "3400.00"}, {"date": "2026-09-04", "customer": "Sunil Varma", "phone": "+91 99302 44556", "items": "Cash Payment", "debit": "0.00", "credit": "2000.00", "balance": "1400.00"}]}'::jsonb,
  'Current Due Balance = Prior Due + Credit Given - Repayment Received',
  NULL
),

-- ------------------------------------------------------------
-- HR
-- ------------------------------------------------------------
(
  'Salary Sheet',
  'salary-sheet',
  (SELECT id FROM template_categories WHERE slug = 'hr'),
  'HR Managers, Payroll Accountants, Business Owners',
  'Monthly payroll calculation sheet with basic pay, HRA, allowances, PF, ESI, professional tax, and net payable salary.',
  'XLSX / CSV / PDF',
  '1.0.0',
  'Standard Business Format — Original',
  'Open Business Format — Free for commercial & operational use',
  '["Emp ID", "Employee Name", "Designation", "Basic Pay (₹)", "HRA (₹)", "Special Allowance (₹)", "Gross Salary (₹)", "PF Deduction (₹)", "TDS / PT (₹)", "Net Payable (₹)"]'::jsonb,
  '{"columns": [{"key": "empId", "label": "Emp ID", "type": "text"}, {"key": "name", "label": "Name", "type": "text"}, {"key": "designation", "label": "Designation", "type": "text"}, {"key": "basic", "label": "Basic (₹)", "type": "currency"}, {"key": "hra", "label": "HRA (₹)", "type": "currency"}, {"key": "allowance", "label": "Allowance (₹)", "type": "currency"}, {"key": "gross", "label": "Gross (₹)", "type": "formula", "formula": "Basic + HRA + Allowance"}, {"key": "pf", "label": "PF (₹)", "type": "currency"}, {"key": "pt", "label": "PT / TDS (₹)", "type": "currency"}, {"key": "net", "label": "Net Salary (₹)", "type": "formula", "formula": "Gross - PF - PT"}]}'::jsonb,
  '{"rows": [{"empId": "EMP-001", "name": "Deepak Sharma", "designation": "Master Carpenter", "basic": "22000.00", "hra": "8800.00", "allowance": "4200.00", "gross": "35000.00", "pf": "2640.00", "pt": "200.00", "net": "32160.00"}, {"empId": "EMP-002", "name": "Kavita Rao", "designation": "Showroom Manager", "basic": "28000.00", "hra": "11200.00", "allowance": "5800.00", "gross": "45000.00", "pf": "3360.00", "pt": "200.00", "net": "41440.00"}]}'::jsonb,
  'Gross = Basic + HRA + Allowances; Net Salary = Gross - PF - PT - TDS',
  NULL
),
(
  'Attendance Register',
  'attendance-register',
  (SELECT id FROM template_categories WHERE slug = 'hr'),
  'Timekeepers, Factory Managers, HR',
  'Monthly employee attendance register with present, absent, leave, half-day records, and total billable workdays.',
  'XLSX / CSV / PDF',
  '1.0.0',
  'Standard Business Format — Original',
  'Open Business Format — Free for commercial & operational use',
  '["Emp ID", "Employee Name", "Department", "Total Days", "Present Days", "Paid Leaves", "Absents", "Payable Days"]'::jsonb,
  '{"columns": [{"key": "empId", "label": "Emp ID", "type": "text"}, {"key": "name", "label": "Name", "type": "text"}, {"key": "dept", "label": "Department", "type": "text"}, {"key": "total", "label": "Month Days", "type": "number"}, {"key": "present", "label": "Present", "type": "number"}, {"key": "leave", "label": "Paid Leaves", "type": "number"}, {"key": "absent", "label": "Absents", "type": "number"}, {"key": "payable", "label": "Payable Days", "type": "formula", "formula": "Present + Paid Leaves"}]}'::jsonb,
  '{"rows": [{"empId": "EMP-001", "name": "Deepak Sharma", "dept": "Workshop", "total": 30, "present": 25, "leave": 2, "absent": 3, "payable": 27}]}'::jsonb,
  'Payable Days = Present Days + Approved Paid Leaves',
  NULL
),

-- ------------------------------------------------------------
-- PROJECTS
-- ------------------------------------------------------------
(
  'Project Budget',
  'project-budget',
  (SELECT id FROM template_categories WHERE slug = 'project-management'),
  'Project Managers, Architects, Consultants',
  'High-level project budget template grouping cost categories, estimated expenses, actual disbursements, and variance.',
  'XLSX / CSV / PDF',
  '1.0.0',
  'Standard Business Format — Original',
  'Open Business Format — Free for commercial & operational use',
  '["WBS Code", "Category / Phase", "Planned Budget (₹)", "Committed / Spent (₹)", "Remaining Budget (₹)", "% Spent"]'::jsonb,
  '{"columns": [{"key": "wbs", "label": "WBS Code", "type": "text"}, {"key": "category", "label": "Category", "type": "text"}, {"key": "budget", "label": "Planned Budget (₹)", "type": "currency"}, {"key": "spent", "label": "Spent (₹)", "type": "currency"}, {"key": "remaining", "label": "Remaining (₹)", "type": "formula", "formula": "Budget - Spent"}, {"key": "pct", "label": "% Spent", "type": "formula", "formula": "(Spent / Budget) * 100"}]}'::jsonb,
  '{"rows": [{"wbs": "1.0", "category": "Architectural Design & Drawings", "budget": "60000.00", "spent": "60000.00", "remaining": "0.00", "pct": "100.0%"}, {"wbs": "2.0", "category": "Modular Furniture Fabrication", "budget": "350000.00", "spent": "210000.00", "remaining": "140000.00", "pct": "60.0%"}, {"wbs": "3.0", "category": "Electrical & Accent Lighting", "budget": "80000.00", "spent": "45000.00", "remaining": "35000.00", "pct": "56.3%"}]}'::jsonb,
  'Remaining Budget = Planned Budget - Committed / Spent; % Spent = (Spent / Budget) * 100',
  NULL
),

-- ------------------------------------------------------------
-- BUSINESS
-- ------------------------------------------------------------
(
  'Monthly Business Dashboard',
  'monthly-business-dashboard',
  (SELECT id FROM template_categories WHERE slug = 'small-business'),
  'Founders, Business Owners, General Managers',
  'Executive business summary tracker highlighting total revenue, direct costs, overheads, net operating profit, and gross margin.',
  'XLSX / CSV / PDF',
  '1.0.0',
  'Standard Business Format — Original',
  'Open Business Format — Free for commercial & operational use',
  '["Month", "Gross Sales (₹)", "Material Purchases (₹)", "Direct Wages (₹)", "Operating Expenses (₹)", "Net Operating Income (₹)", "Profit Margin (%)"]'::jsonb,
  '{"columns": [{"key": "month", "label": "Month", "type": "text"}, {"key": "sales", "label": "Gross Sales (₹)", "type": "currency"}, {"key": "purchases", "label": "Purchases (₹)", "type": "currency"}, {"key": "wages", "label": "Wages (₹)", "type": "currency"}, {"key": "opex", "label": "Opex (₹)", "type": "currency"}, {"key": "net", "label": "Net Income (₹)", "type": "formula", "formula": "Sales - (Purchases + Wages + Opex)"}, {"key": "margin", "label": "Margin %", "type": "formula", "formula": "(Net / Sales) * 100"}]}'::jsonb,
  '{"rows": [{"month": "July 2026", "sales": "920000.00", "purchases": "380000.00", "wages": "160000.00", "opex": "95000.00", "net": "285000.00", "margin": "31.0%"}, {"month": "August 2026", "sales": "1050000.00", "purchases": "440000.00", "wages": "170000.00", "opex": "102000.00", "net": "338000.00", "margin": "32.2%"}]}'::jsonb,
  'Net Operating Income = Sales - (Purchases + Wages + Opex); Margin % = (Net / Sales) * 100',
  NULL
)
ON CONFLICT (slug) DO UPDATE SET
  name = EXCLUDED.name,
  category_id = EXCLUDED.category_id,
  profession = EXCLUDED.profession,
  description = EXCLUDED.description,
  fields_json = EXCLUDED.fields_json,
  structure_json = EXCLUDED.structure_json,
  preview_data_json = EXCLUDED.preview_data_json,
  formula_notes = EXCLUDED.formula_notes,
  erp_data_source = EXCLUDED.erp_data_source,
  updated_at = now();
